### ISSUE TITLE
单人游戏-选择世界 取消按钮失效

### ISSUE THREAD

**Issue by AdminHcat** [XiaoXianHW/EasyLAN#4]
1.12.2版本测试
加入EasyLAN后无法点击 单人游戏-选择世界 中的取消按钮，
![image](https://github.com/XiaoXianHW/EasyLAN/assets/50044729/cdb60cc8-37f5-4e36-959a-1ae4a6456448)

我注意到布局由原版的`net.minecraft.client.gui.GuiWorldSelection`被替换为 `org.xiaoxian.gui.GuiWorldSelectionEdit$GuiWorldSelectionModified`，可能是引起问题的原因

**Comment by XiaoXianHW** [comment]
感谢使用和提出的反馈.
的确是`GuiWorldSelectionEdit`潜在出现了遗漏的问题，先暂时使用Esc键进行返回，这一问题将会在未来版本中进行修复，感谢谅解

**Comment by Omgise** [comment]
1.7.10也有这个问题

**Comment by XiaoXianHW** [comment]
EasyLAN v1.2已修复
