### ISSUE TITLE
[1.7.10]EasyLAN主设置按钮和Advanced World Selection冲突

### ISSUE THREAD

**Issue by Omgise** [XiaoXianHW/EasyLAN#5]
![image](https://github.com/XiaoXianHW/EasyLAN/assets/106000018/00530c4c-81e2-48cc-a92b-384258c87910)

**Comment by XiaoXianHW** [comment]
**感谢您的反馈和使用，此问题已加入工作列表，问题会随着新版本进行修复，目前先暂时只选择任一mod游玩**（最近在准备考试，放假了会及时修复，请谅解🙏）

**Comment by Omgise** [comment]
没关系，努力考试吧，加油！

**Comment by Omgise** [comment]
@XiaoXianHW 在修了吗（

**Comment by XiaoXianHW** [comment]
> @XiaoXianHW 在修了吗（

在修了在修了（最近在忙着着手其他项目），因为修一次要全版本都改代码，而且冲突的mod太多了很多人也在b站评论发这个问题，我实在没什么思绪修好它（没怎么学过mod开发，这个mod只是初学的作品），目前在考虑将这个按钮放置在其他位置，如果有更好的方法欢迎提一下（实在抱歉了

**Comment by Omgise** [comment]
@XiaoXianHW  把EasyLAN主设置按钮放进多人游戏设置里怎么样？
![image](https://github.com/XiaoXianHW/EasyLAN/assets/106000018/f127d292-a0ef-4244-9e15-7ff11d7cfda7)

**Comment by Omgise** [comment]
这样不仅美观，而且不会和某些修改界面的mod冲突

**Comment by XiaoXianHW** [comment]
v1.5已尝试修复

**Comment by Omgise** [comment]
v1.5还是冲突
![image](https://github.com/user-attachments/assets/769bd25a-6f2e-405e-a1b6-c5760cd3c45b)

**Comment by XiaoXianHW** [comment]
[EasyLAN-v1.5Edit-1.7.10.zip](https://github.com/user-attachments/files/16780582/EasyLAN-v1.5Edit-1.7.10.zip)
冲突比较少见，加上Advanced World Selection闭源且停更，用我上传的这个版本吧，把GuiWorldSelectionEdit给去掉了，需要Gui设置的话可以到首页的Mods里找到EasyLAN-配置（Config）进行修改，初学Mod开发我实在没什么精力来处理这种冲突的问题，抱歉

**Comment by Omgise** [comment]
> [EasyLAN-v1.5Edit-1.7.10.zip](https://github.com/user-attachments/files/16780582/EasyLAN-v1.5Edit-1.7.10.zip) 冲突比较少见，加上Advanced World Selection闭源且停更，用我上传的这个版本吧，把GuiWorldSelectionEdit给去掉了，需要Gui设置的话可以到首页的Mods里找到EasyLAN-配置（Config）进行修改，初学Mod开发我实在没什么精力来处理这种冲突的问题，抱歉

感谢大佬！

**Comment by Omgise** [comment]
现在没事了，我发现有mod可以替代Advanced World Selection了
